- name: Install dependencies
  run: |
    pip install --upgrade pip
    pip install -r requirements.txt

- name: Register python3 kernel
  run: |
    python -m ipykernel install --user --name python3 --display-name "Python 3"

- name: Execute ETL Notebook
  run: |
    papermill notebooks/pyspark_etl.ipynb notebooks/pyspark_etl_output.ipynb --kernel python3
