name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # This automatically installs ipykernel, papermill, etc. from your requirements.txt
          pip install -r requirements.txt

      - name: Register python3 kernel
        run: |
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Execute ETL Notebook
        run: |
          papermill notebooks/pyspark_etl.ipynb notebooks/pyspark_etl_output.ipynb --kernel python3

      - name: Execute ML Training Notebook
        run: |
          papermill notebooks/ml_training.ipynb notebooks/ml_training_output.ipynb --kernel python3
